import { useEffect, useState, useCallback } from 'react';
import {
  Typography, Grid, TextField, Button, MenuItem, Box, Stack, Alert,
  CircularProgress, Chip, InputAdornment, Paper,
} from '@mui/material';
import { alpha } from '@mui/material/styles';
import {
  AssessmentOutlined, DownloadOutlined, HistoryOutlined, CalendarTodayOutlined,
  DescriptionOutlined, PlayArrowOutlined, InboxOutlined,
} from '@mui/icons-material';
import { toast } from 'react-toastify';
import DataTable from '../../components/DataTable';
import {
  PremiumPageCard, PremiumSection, adminFieldSx, premiumButtonSx,
  premiumPaperSx, emptyStateSx,
} from '../../components/PremiumPageLayout';
import api from '../../services/api';
import useSystemDateTime from '../../hooks/useSystemDateTime';
import { refreshNotificationBadge } from '../../utils/notificationRefresh';
import PageLoader from '../../components/PageLoader';

const REPORT_TYPES = [
  { value: 'conference', label: 'Conference Report' },
  { value: 'patient', label: 'Patient Report' },
  { value: 'gp', label: 'GP Report' },
  { value: 'ahp', label: 'AHP Report' },
  { value: 'activity', label: 'Activity Report' },
  { value: 'login', label: 'Login Report' },
];

const Reports = () => {
  const { formatDateTime } = useSystemDateTime();
  const [form, setForm] = useState({ report_type: 'conference', start_date: '', end_date: '' });
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [history, setHistory] = useState([]);
  const [historyLoading, setHistoryLoading] = useState(true);
  const [historyError, setHistoryError] = useState('');
  const [historyFilter, setHistoryFilter] = useState('');

  const fetchHistory = useCallback(async () => {
    setHistoryLoading(true);
    setHistoryError('');
    try {
      const { data } = await api.get('/reports/history');
      setHistory(data.data || []);
    } catch {
      setHistoryError('Failed to load report history');
    } finally {
      setHistoryLoading(false);
    }
  }, []);

  useEffect(() => { fetchHistory(); }, [fetchHistory]);

  const handleGenerate = async (format) => {
    if (!form.start_date || !form.end_date) {
      toast.error('Please select start and end dates');
      return;
    }
    setLoading(true);
    setResult(null);
    try {
      const { data } = await api.post(
        `/reports/generate${format === 'csv' ? '?format=csv' : ''}`,
        form,
        format === 'csv' ? { responseType: 'blob' } : {},
      );
      if (format === 'csv') {
        const url = window.URL.createObjectURL(new Blob([data]));
        const link = document.createElement('a');
        link.href = url;
        link.download = `${form.report_type}_report.csv`;
        link.click();
        window.URL.revokeObjectURL(url);
        toast.success('CSV exported successfully');
        fetchHistory();
        refreshNotificationBadge();
      } else {
        setResult(data.data);
        toast.success('Report generated successfully');
        fetchHistory();
        refreshNotificationBadge();
      }
    } catch {
      toast.error('Report generation failed');
    } finally {
      setLoading(false);
    }
  };

  const filteredHistory = history.filter((h) => {
    if (!historyFilter) return true;
    const q = historyFilter.toLowerCase();
    return (
      h.title?.toLowerCase().includes(q)
      || h.report_type?.toLowerCase().includes(q)
      || h.generated_by_email?.toLowerCase().includes(q)
    );
  });

  const historyColumns = [
    { field: 'title', headerName: 'Report' },
    {
      field: 'report_type',
      headerName: 'Type',
      render: (r) => (
        <Chip
          label={r.report_type}
          size="small"
          sx={{
            fontWeight: 600,
            fontSize: '0.75rem',
            bgcolor: (theme) => alpha(theme.palette.primary.main, 0.08),
            color: 'primary.main',
            border: '1px solid',
            borderColor: (theme) => alpha(theme.palette.primary.main, 0.15),
          }}
        />
      ),
    },
    { field: 'generated_by_email', headerName: 'Generated By', render: (r) => r.generated_by_email || '—' },
    {
      field: 'created_at',
      headerName: 'Generated At',
      render: (r) => formatDateTime(r.created_at),
    },
  ];

  const fieldIcon = (Icon) => (
    <InputAdornment position="start" sx={{ ml: 0.5 }}>
      <Icon sx={{ fontSize: 20, color: 'primary.main', opacity: 0.85 }} />
    </InputAdornment>
  );

  return (
    <Stack spacing={2.5}>
      <PremiumPageCard
        icon={AssessmentOutlined}
        title="Reports & Analytics"
        subtitle="Generate, preview, and export system reports for operational review"
      >
        <Grid container spacing={2.5} sx={{ alignItems: 'stretch' }}>
          <Grid size={{ xs: 12, lg: 4 }}>
            <PremiumSection
              icon={DescriptionOutlined}
              title="Report Generator"
              subtitle="Select type and date range"
            >
              <Stack spacing={2}>
                <TextField
                  fullWidth
                  size="small"
                  select
                  label="Report Type"
                  value={form.report_type}
                  onChange={(e) => setForm({ ...form, report_type: e.target.value })}
                  sx={adminFieldSx}
                  slotProps={{
                    inputLabel: { shrink: true },
                    input: { startAdornment: fieldIcon(AssessmentOutlined) },
                  }}
                >
                  {REPORT_TYPES.map((r) => <MenuItem key={r.value} value={r.value}>{r.label}</MenuItem>)}
                </TextField>
                <TextField
                  fullWidth
                  size="small"
                  type="date"
                  label="Start Date"
                  value={form.start_date}
                  onChange={(e) => setForm({ ...form, start_date: e.target.value })}
                  sx={adminFieldSx}
                  slotProps={{
                    inputLabel: { shrink: true },
                    input: { startAdornment: fieldIcon(CalendarTodayOutlined) },
                  }}
                />
                <TextField
                  fullWidth
                  size="small"
                  type="date"
                  label="End Date"
                  value={form.end_date}
                  onChange={(e) => setForm({ ...form, end_date: e.target.value })}
                  sx={adminFieldSx}
                  slotProps={{
                    inputLabel: { shrink: true },
                    input: { startAdornment: fieldIcon(CalendarTodayOutlined) },
                  }}
                />
                <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1.5} sx={{ pt: 0.5 }}>
                  <Button
                    variant="contained"
                    onClick={() => handleGenerate('json')}
                    disabled={loading}
                    fullWidth
                    startIcon={loading ? <CircularProgress size={16} color="inherit" /> : <PlayArrowOutlined />}
                    sx={premiumButtonSx}
                  >
                    {loading ? 'Generating...' : 'Generate'}
                  </Button>
                  <Button
                    variant="outlined"
                    onClick={() => handleGenerate('csv')}
                    disabled={loading}
                    fullWidth
                    startIcon={<DownloadOutlined />}
                    sx={{ borderRadius: 2, fontWeight: 600, py: 1 }}
                  >
                    Export CSV
                  </Button>
                </Stack>
              </Stack>
            </PremiumSection>
          </Grid>

          <Grid size={{ xs: 12, lg: 8 }}>
            <Paper elevation={0} sx={{ ...premiumPaperSx, height: '100%', p: { xs: 2, sm: 2.5 } }}>
              <Stack direction="row" spacing={1.25} sx={{ alignItems: 'center', mb: 2 }}>
                <Box
                  sx={{
                    width: 36,
                    height: 36,
                    borderRadius: '50%',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    bgcolor: (theme) => alpha(theme.palette.primary.main, 0.08),
                    color: 'primary.main',
                  }}
                >
                  <DescriptionOutlined sx={{ fontSize: 18 }} />
                </Box>
                <Box>
                  <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>Report Preview</Typography>
                  <Typography variant="caption" color="text.secondary">First 10 records before export</Typography>
                </Box>
              </Stack>

              {loading ? (
                <PageLoader message="Generating report..." />
              ) : result ? (
                <>
                  <Box
                    sx={{
                      mb: 2,
                      p: 2,
                      borderRadius: 2,
                      border: '1px solid',
                      borderColor: (theme) => alpha(theme.palette.primary.main, 0.15),
                      bgcolor: (theme) => alpha(theme.palette.primary.main, 0.04),
                    }}
                  >
                    <Typography variant="subtitle2" sx={{ fontWeight: 700, color: 'primary.main' }}>
                      {result.title}
                    </Typography>
                    <Typography variant="body2" color="text.secondary" sx={{ fontWeight: 500 }}>
                      {result.count} records found
                    </Typography>
                  </Box>
                  <Box
                    component="pre"
                    sx={{
                      overflow: 'auto',
                      maxHeight: 320,
                      fontSize: '0.75rem',
                      bgcolor: 'background.default',
                      p: 2,
                      borderRadius: 2,
                      border: '1px solid',
                      borderColor: 'divider',
                      m: 0,
                      fontFamily: 'ui-monospace, monospace',
                    }}
                  >
                    {JSON.stringify(result.records?.slice(0, 10), null, 2)}
                  </Box>
                </>
              ) : (
                <Box sx={emptyStateSx}>
                  <InboxOutlined sx={{ fontSize: 40, color: 'text.disabled', mb: 1.5 }} />
                  <Typography variant="body2" color="text.secondary" sx={{ fontWeight: 500 }}>
                    Select report parameters and click Generate
                  </Typography>
                </Box>
              )}
            </Paper>
          </Grid>
        </Grid>
      </PremiumPageCard>

      <Stack direction="row" spacing={1.25} sx={{ alignItems: 'center', px: 0.5 }}>
        <Box
          sx={{
            width: 32,
            height: 32,
            borderRadius: '50%',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            bgcolor: (theme) => alpha(theme.palette.primary.main, 0.08),
            color: 'primary.main',
          }}
        >
          <HistoryOutlined sx={{ fontSize: 17 }} />
        </Box>
        <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>Report History</Typography>
      </Stack>

      {historyError && <Alert severity="error" sx={{ borderRadius: 2 }}>{historyError}</Alert>}

      <DataTable
        title="Recently Generated Reports"
        columns={historyColumns}
        rows={filteredHistory}
        loading={historyLoading}
        onSearch={(v) => setHistoryFilter(v)}
        searchPlaceholder="Filter by type, title, or user..."
        actions={false}
      />
    </Stack>
  );
};

export default Reports;
